### ISSUE TITLE
Error stopping node: TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by me6ran** [fellinga/node-red-contrib-ui-time-scheduler#17]
Hi,
Thanks for the great job you did for this node,
I just installed V 0.4.6, I found the node in the proper location (within my dashboard nodes)
I dragged it in my flow page, then double click on it, then assigned an appropriate group to the node, finally when I hit "deploy", it return the error:
 **Error stopping node: TypeError: Cannot read property 'length' of undefined**

I am not sure that it is not working because of my Node-red version V0.18.4 (kind of old) 

this is a snippet of nod-red-log, I hope it can help:
`at start (/usr/lib/node_modules/node-red/red/runtime/nodes/flows/index.js:307:29)
    at /usr/lib/node_modules/node-red/red/runtime/nodes/flows/index.js:144:21
    at tryCatchReject (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:804:4)
    at Fulfilled.when (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:592:4)
    at Pending.run (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/usr/lib/node_modules/node-red/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/usr/lib/node_modules/node-red/node_modules/when/lib/Scheduler.js:27:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
15 Dec 21:42:15 - [error] Error stopping node: TypeError: Cannot read property 'length' of undefined
TimeSchedulerNode: TypeError: RED.require is not a function
    at new TimeSchedulerNode (/home/pi/.node-red/node_modules/node-red-contrib-ui-time-scheduler/time-scheduler.js:204:14)
    at createNode (/usr/lib/node_modules/node-red/red/runtime/nodes/flows/Flow.js:305:18)
    at Flow.start (/usr/lib/node_modules/node-red/red/runtime/nodes/flows/Flow.js:89:35)
    at start (/usr/lib/node_modules/node-red/red/runtime/nodes/flows/index.js:307:29)
    at /usr/lib/node_modules/node-red/red/runtime/nodes/flows/index.js:144:21
    at tryCatchReject (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:804:4)
    at Fulfilled.when (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:592:4)
    at Pending.run (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/usr/lib/node_modules/node-red/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/usr/lib/node_modules/node-red/node_modules/when/lib/Scheduler.js:27:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
`

Thanks.

**Comment by fellinga** [comment]
Hi Robert!

I am actually more concerned about "**RED.require is not a function**". What version of the Node-Red-Dashboard are you using?

**Comment by me6ran** [comment]
> Hi Robert!
> 
> I am actually more concerned about "**RED.require is not a function**". What version of the Node-Red-Dashboard are you using?

I am using version 2.9.0 
![image](https://user-images.githubusercontent.com/17004677/102376579-a1510900-3f78-11eb-90ac-0f53bfbdae73.png)

**Comment by fellinga** [comment]
Custom UI nodes (like this one) can only be used from 2.10.0 upwards. See [this link](https://flows.nodered.org/node/node-red-dashboard), it says: **From version 2.10.0 you can create and **install** widget nodes like other Node-RED nodes. See the Wiki for more information.**

Can you upgrade to at least 2.10.0 (which is from Oct 22, 2018) and see if it works then?

**Comment by me6ran** [comment]
> Custom UI nodes (like this one), sometimes referred as widgets, can only be used from 2.10.0 upwards. See [this link](https://flows.nodered.org/node/node-red-dashboard), it says: **From version 2.10.0 you can create and **install** widget nodes like other Node-RED nodes.**
> 
> Can you upgrade to at least 2.10.0 (which is from Oct 22, 2018) and see if it works then?


oh I see, I have not seen that version thing in "dashboard" page 
thanks for pointing this out,
I will try to upgrade it, and will let you know.

**Comment by fellinga** [comment]
> thanks for pointing this out,

You are welcome!
Just one other thing, it seems 2.9.5 is the last dashboard version to support node v6 - so make sure to update that as well if you are still on v6!

**Comment by me6ran** [comment]
> > thanks for pointing this out,
> 
> You are welcome!
> Just one other thing, it seems 2.9.5 is the last dashboard version to support node v6 - so make sure to update that as well if you are still on v6!


ok, I upgraded "Dashboard" to 2.10.0, and still getting the same error:
`16 Dec 20:35:35 - [error] Error stopping node: TypeError: Cannot read property 'length' of undefined
TimeSchedulerNode: TypeError: RED.require is not a function
    at new TimeSchedulerNode (/home/pi/.node-red/node_modules/node-red-contrib-ui-time-scheduler/time-scheduler.js:204:14)
    at createNode (/usr/lib/node_modules/node-red/red/runtime/nodes/flows/Flow.js:305:18)
    at Flow.start (/usr/lib/node_modules/node-red/red/runtime/nodes/flows/Flow.js:89:35)
    at start (/usr/lib/node_modules/node-red/red/runtime/nodes/flows/index.js:307:29)
    at /usr/lib/node_modules/node-red/red/runtime/nodes/flows/index.js:144:21
    at tryCatchReject (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:804:4)
    at Fulfilled.when (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:592:4)
    at Pending.run (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/usr/lib/node_modules/node-red/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/usr/lib/node_modules/node-red/node_modules/when/lib/Scheduler.js:27:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
`
Versions:
    - node : v8.11.1
    - node-red-dashboard   2.10.0
    - node-red  0.18.4

**Comment by fellinga** [comment]
Thank you for the update!

I did some testing in my virtual machine this morning. I was able to reproduce the exact same error that you posted with 0.18.4 & 2.10.0. The function RED.require that (I think) every widget is actively using to check if the dashboard is installed was only added to node-red with version [0.19](https://github.com/node-red/node-red/releases/tag/0.19.0). After upgrading node-red from 0.18.4 to 0.19.0 the widget finally worked.

Please note: I am using css-color-variables for the nodes colors. I also found out today that they were added to the dashboard with [2.15.4](https://github.com/node-red/node-red-dashboard/releases/tag/2.15.4) which means the node works with 2.10.0 but it is a lot prettier with 2.15.4 and up.

Please let me know if this helps!

**Comment by me6ran** [comment]
Thanks for sorting this out, that explains everything!
At least we now know what is the minimum perquisites.

I believe the ticket can be closed.

**Comment by fellinga** [comment]
Yes it was definitely helpful to determine the minimum prerequisites, I'll add that to the README soon.

Just out of curiosity - does anything prevent you from upgrading to 0.19 or the latest version?

**Comment by me6ran** [comment]
> Yes it was definitely helpful to determine the minimum prerequisites, I'll add that to the README soon.
> 
> Just out of curiosity - does anything prevent you from upgrading to 0.19 or the latest version?


yup, that is a good question, the  reason is that I do not have a unit test, and all the steps I did, were on production unit!! (yeah I am fearless, but not anymore =))) )
that is why I try not to play with it, and put the system in risk. I am not sure, maybe some day, I get drunk and upgrade everything on production unit. ;)

have a great time, and thanks for your kindly support.
